name: W2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: w2 - 128 - 128
      run: python w2/main.py 128 128
    - name: w2 - 128 - 64
      run: python w2/main.py 128 64
    - name: w2 - 128 - 32
      run: python w2/main.py 128 32
    - name: w2 - 128 - 16
      run: python w2/main.py 128 16
    - name: w2 - 128 - 8
      run: python w2/main.py 128 8
    - name: w2 - 64 - 64
      run: python w2/main.py 64 64
    - name: w2 - 64 - 32
      run: python w2/main.py 64 32
    - name: w2 - 64 - 16
      run: python w2/main.py 64 16
    - name: w2 - 64 - 8
      run: python w2/main.py 64 8
    - name: w2 - 32 - 32
      run: python w2/main.py 32 32
    - name: w2 - 32 - 16
      run: python w2/main.py 32 16
    - name: w2 - 32 - 8
      run: python w2/main.py 32 8
    - name: w2 - 16 - 16
      run: python w2/main.py 16 8
    - name: w2 - 16 - 8
      run: python w2/main.py 16 8
    - name: w2 - 8 - 8
      run: python w2/main.py 8 8